In [ ]:
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
a = np.array([1,2,3,5,7,12])
print(a)

[ 1  2  3  5  7 12]


In [ ]:
a[2] = 10
print(a)

[ 1  2 10  5  7 12]


In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(0,100,11) # creates arrays with evenly spaced numbers within a specific range

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

###Multi-dimensional* Arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [23]:
n[2] = [1,1,1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [24]:
n[:, 2] = [0,1,2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

###Randomly-Generated Arrays
Numpy can create arrays filled with random numbers. To ensure reproducebility, you can set a seed using np.random.seed():

Everytime you run this code this np.random.seed(42), it will generatre the exact same three random numbers. If you remove or change the seed value, the sequence of random numbers will change.

In [27]:
np.random.rand(3)

array([0.62113383, 0.52914209, 0.13457995])

In [25]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

#### Element wise Operation

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
b= (10 + (a * 2))
b

array([10, 12, 14, 16, 18])

#### Comparision Operations

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
a >= 2

array([False, False,  True,  True,  True])

In [35]:
b

array([10, 12, 14, 16, 18])

In [36]:
a > b

array([False, False, False, False, False])

### Summarize

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a.std()

1.4142135623730951

In [39]:
a.min()

0

In [40]:
a.max()

4

In [41]:
a.sum()

10